packages:
  - apps/*
  - packages/*
overrides:
  'multer@<2.3.0': 2.3.0
  'path-to-regexp@>=8.0.0 <8.4.0': 8.4.0
  'lodash@<4.18.1': 4.18.1
  'js-yaml@>=4.0.0 <4.3.2': 4.3.2
  'uuid@>=9.0.0 <11.1.1': 11.1.1
  'deepmerge-ts@<8.0.0': 8.0.0
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  sharp: true
  argon2: true
  '@nestjs/core': false
  msgpackr-extract: false
  unrs-resolver: true
  '@scarf/scarf': false
minimumReleaseAgeExclude:
  - '@aws-sdk/checksums@3.1001.1'
  - '@aws-sdk/client-s3@3.1138.0'
  - '@aws-sdk/core@3.978.1'
  - '@aws-sdk/credential-provider-env@3.972.72'
  - '@aws-sdk/credential-provider-http@3.972.74'
  - '@aws-sdk/credential-provider-ini@3.973.17'
  - '@aws-sdk/credential-provider-login@3.972.79'
  - '@aws-sdk/credential-provider-node@3.972.84'
  - '@aws-sdk/credential-provider-process@3.972.72'
  - '@aws-sdk/credential-provider-sso@3.973.16'
  - '@aws-sdk/credential-provider-web-identity@3.972.78'
  - '@aws-sdk/middleware-sdk-s3@3.972.77'
  - '@aws-sdk/nested-clients@3.997.46'
  - '@aws-sdk/signature-v4-multi-region@3.996.47'
  - '@aws-sdk/token-providers@3.1138.0'
  - '@aws-sdk/types@3.974.6'
  - '@aws-sdk/xml-builder@3.972.41'
  - '@smithy/core@3.35.0'
  - '@smithy/types@4.19.0'
