import { useEffect, useRef, useState } from 'react';
import { Alert, App, Button, Modal } from 'antd';
import { CameraOutlined, ClearOutlined, SaveOutlined } from '@ant-design/icons';
import { AssetImage } from './Common';
import { api, errorText } from '../lib/api';
import type { MedicalImage, Roi } from '../lib/types';

export function Camera({ open, onClose, onCapture }: { open: boolean; onClose: () => void; onCapture: (file: File) => void }) {
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const [error, setError] = useState(''); const [ready, setReady] = useState(false);
  useEffect(() => { if (!open) return; let active = true; setError(''); setReady(false); if (!navigator.mediaDevices?.getUserMedia) { setError('Kamera uchun HTTPS yoki localhost kerak. Galereyadan surat tanlang.'); return; } navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' }, audio: false }).then(s => { if (!active) { s.getTracks().forEach(t => t.stop()); return; } stream.current = s; if (video.current) video.current.srcObject = s; }).catch(() => setError('Kamera ochilmadi. Brauzer ruxsatini tekshiring yoki galereyadan surat tanlang.')); return () => { active = false; stream.current?.getTracks().forEach(t => t.stop()); stream.current = null; }; }, [open]);
  function capture() { const element = video.current; if (!element?.videoWidth) return; const canvas = document.createElement('canvas'); canvas.width = element.videoWidth; canvas.height = element.videoHeight; canvas.getContext('2d')?.drawImage(element, 0, 0); canvas.toBlob(blob => { if (blob) { onCapture(new File([blob], `kamera-${Date.now()}.jpg`, { type: 'image/jpeg' })); onClose(); } }, 'image/jpeg', 0.92); }
  return <Modal open={open} title="Kamera orqali surat olish" onCancel={onClose} destroyOnHidden footer={<Button type="primary" icon={<CameraOutlined/>} disabled={!ready || !!error} onClick={capture}>Suratga olish</Button>}>{error && <Alert type="warning" showIcon message={error}/>}<video className="camera-video" ref={video} autoPlay playsInline muted onLoadedMetadata={() => setReady(true)}/><p className="muted">Kamerani fokuslang, zararlangan joy to‘liq ko‘rinsin.</p></Modal>;
}
export function RoiEditor({ image, analysisId, onClose, onSaved }: { image: MedicalImage | null; analysisId: string; onClose: () => void; onSaved: () => void }) {
  const [roi, setRoi] = useState<Roi | null>(null); const [anchor, setAnchor] = useState<{ x: number; y: number } | null>(null); const [pending, setPending] = useState(false); const { message } = App.useApp(); const frame = useRef<HTMLDivElement>(null);
  useEffect(() => setRoi(image?.roi ?? null), [image]);
  const point = (e: React.PointerEvent) => { const r = frame.current!.getBoundingClientRect(); return { x: Math.max(0, Math.min(1, (e.clientX - r.left) / r.width)), y: Math.max(0, Math.min(1, (e.clientY - r.top) / r.height)) }; };
  async function save() { if (!image) return; setPending(true); try { await api.patch(`/analyses/${analysisId}/images/${image.id}/roi`, roi && roi.width > 0.01 && roi.height > 0.01 ? roi : { roi: null }); onSaved(); onClose(); message.success('Belgilangan hudud saqlandi'); } catch (e) { message.error(errorText(e)); } finally { setPending(false); } }
  return <Modal open={!!image} title="Kuzatilayotgan hududni belgilang" onCancel={onClose} footer={<><Button icon={<ClearOutlined/>} onClick={() => setRoi(null)}>Belgini tozalash</Button><Button type="primary" icon={<SaveOutlined/>} loading={pending} onClick={() => { void save(); }}>Saqlash</Button></>}>{image && <><p>Sichqoncha yoki barmoq bilan to‘rtburchak chizing. Bu sizning belgingiz — AI segmentatsiyasi emas.</p><div ref={frame} className="roi-frame" style={{ aspectRatio: `${image.width}/${image.height}` }} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); setAnchor(point(e)); setRoi(null); }} onPointerMove={e => { if (!anchor) return; const p = point(e); setRoi({ x: Math.min(anchor.x, p.x), y: Math.min(anchor.y, p.y), width: Math.abs(anchor.x - p.x), height: Math.abs(anchor.y - p.y) }); }} onPointerUp={() => setAnchor(null)} onPointerCancel={() => setAnchor(null)}><AssetImage id={image.id} alt="Hududni belgilash uchun yuklangan surat"/>{roi && <div className="roi-selection" style={{ left: `${roi.x * 100}%`, top: `${roi.y * 100}%`, width: `${roi.width * 100}%`, height: `${roi.height * 100}%` }}/>}</div></>}</Modal>;
}
export async function rotateFile(file: File) { const bitmap = await createImageBitmap(file); const canvas = document.createElement('canvas'); canvas.width = bitmap.height; canvas.height = bitmap.width; const ctx = canvas.getContext('2d')!; ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(Math.PI / 2); ctx.drawImage(bitmap, -bitmap.width / 2, -bitmap.height / 2); bitmap.close(); return new Promise<File>((resolve, reject) => canvas.toBlob(blob => blob ? resolve(new File([blob], file.name.replace(/\.[^.]+$/, '') + '.jpg', { type: 'image/jpeg' })) : reject(new Error('Suratni aylantirib bo‘lmadi')), 'image/jpeg', 0.95)); }
export function LocalPreview({ file }: { file: File }) { const [src, setSrc] = useState(''); useEffect(() => { const url = URL.createObjectURL(file); setSrc(url); return () => URL.revokeObjectURL(url); }, [file]); return <img src={src} alt="Yuborishdan oldingi surat"/>; }
