import { useEffect, useState } from 'react';
import { Alert, Avatar, Button, Drawer, Dropdown, App } from 'antd';
import { AppstoreOutlined, HistoryOutlined, PlusOutlined, SettingOutlined, SafetyCertificateOutlined, LogoutOutlined, MenuOutlined, ArrowUpOutlined, UserOutlined } from '@ant-design/icons';
import { NavLink, Navigate, Outlet, useLocation } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import { errorText } from '../lib/api';
import { Brand, DemoNotice, Loading } from './Common';
export default function Shell() {
  const auth = useAuth(); const [drawer, setDrawer] = useState(false); const [online, setOnline] = useState(navigator.onLine); const { message } = App.useApp(); const location = useLocation();
  useEffect(() => { setDrawer(false); window.scrollTo(0, 0); }, [location.pathname]);
  useEffect(() => { const update = () => setOnline(navigator.onLine); window.addEventListener('online', update); window.addEventListener('offline', update); return () => { window.removeEventListener('online', update); window.removeEventListener('offline', update); }; }, []);
  if (auth.loading) return <Loading/>; if (!auth.user) return <Navigate to="/login" replace/>;
  const links = [{ path: '/app', icon: <AppstoreOutlined/>, text: 'Bosh sahifa', end: true }, { path: '/app/analyses/new', icon: <PlusOutlined/>, text: 'Yangi tahlil' }, { path: '/app/history', icon: <HistoryOutlined/>, text: 'Kuzatuvlar tarixi' }, { path: '/app/settings', icon: <SettingOutlined/>, text: 'Sozlamalar' }];
  const sidebar = <><Brand light/><div className="nav-caption">SHAXSIY KABINET</div><nav aria-label="Asosiy menyu">{links.map(link => <NavLink key={link.path} to={link.path} end={link.end} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>{link.icon}{link.text}</NavLink>)}{auth.user.role === 'ADMIN' && <NavLink className="nav-link" to="/admin"><SafetyCertificateOutlined/>Servis boshqaruvi</NavLink>}</nav><div className="sidebar-bottom"><div className="privacy-card"><SafetyCertificateOutlined/><strong>Ma’lumotingiz — o‘zingizniki.</strong><p>Suratlar faqat sizning roziligingiz bilan qayta ishlanadi.</p><NavLink to="/privacy">Maxfiylik haqida <ArrowUpOutlined rotate={45}/></NavLink></div><div className="sidebar-footer">RAQAMLI DERMATOLOG <span>© 2026</span></div></div></>;
  return <div className="app-shell"><aside className="sidebar">{sidebar}</aside><Drawer open={drawer} onClose={() => setDrawer(false)} placement="left" width={282} styles={{ body: { background: '#123f3d', padding: 24, display: 'flex', flexDirection: 'column' } }} title="Menyu">{sidebar}</Drawer><div className="main-shell"><header className="topbar"><div className="topbar-left"><Button className="mobile-menu" type="text" icon={<MenuOutlined/>} aria-label="Menyuni ochish" onClick={() => setDrawer(true)}/><span className="topbar-label">Teri salomatligi uchun shaxsiy makon</span></div><div className="topbar-right"><span className="prototype-pill"><i/> Skrining prototipi</span><Dropdown menu={{ items: [{ key: 'settings', label: <NavLink to="/app/settings">Hisob sozlamalari</NavLink>, icon: <SettingOutlined/> }, { key: 'logout', label: 'Chiqish', icon: <LogoutOutlined/>, onClick: () => { void auth.logout().catch(e => message.error(errorText(e))); } }] }}><button className="user-button"><Avatar size={34} style={{ background: '#e3eadd', color: '#244c3e' }} icon={<UserOutlined/>}/><span>{auth.user.name.split(' ')[0]}</span></button></Dropdown></div></header><main className="app-main">{auth.user.isDemo && <DemoNotice account/>}{!online && <Alert className="mb" showIcon type="warning" message="Internet aloqasi yo‘q" description="Suratlar avtomatik yuborilmaydi. Internet qaytgach amalni qayta bajaring."/>}<Outlet/></main><footer className="app-footer"><span>O‘zingizga e’tibor — yaxshi odat.</span><div><NavLink to="/limitations">Tibbiy cheklovlar</NavLink><NavLink to="/privacy">Maxfiylik</NavLink><span>UZ</span></div></footer></div></div>;
}
