import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button, Input, Select } from 'antd';
import { ArrowRightOutlined, FileImageOutlined, PlusOutlined } from '@ant-design/icons';
import { Link } from 'react-router-dom';
import { api, keys } from '../lib/api';
import { date } from '../lib/text';
import type { Analysis, Case, List } from '../lib/types';
import { AssetImage, DemoBadge, EmptyAnalyses, Failure, Loading, PageHeader, Status } from '../components/Common';
export default function History() {
  const [status, setStatus] = useState<string>(); const [risk, setRisk] = useState<string>(); const [caseId, setCaseId] = useState<string>(); const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState(''); const [cursors, setCursors] = useState<(string | undefined)[]>([undefined]); const cursor = cursors.at(-1);
  const filters = { status, riskLevel: risk, caseId, dateFrom: dateFrom ? `${dateFrom}T00:00:00+05:00` : undefined, dateTo: dateTo ? `${dateTo}T23:59:59.999+05:00` : undefined, cursor, limit: 15 };
  const history = useQuery({ queryKey: [...keys.analyses, filters], queryFn: ({ signal }) => api.get<List<Analysis>>('/analyses', { params: filters, signal }).then(r => r.data) });
  const cases = useQuery({ queryKey: keys.cases, queryFn: ({ signal }) => api.get<List<Case>>('/cases?limit=100', { signal }).then(r => r.data) });
  const resetPage = () => setCursors([undefined]);
  return <><PageHeader eyebrow="VAQT BO‘YICHA KUZATUV" title="Kuzatuvlar tarixi" description="Faqat tarixga saqlashga rozilik bergan tahlillaringiz shu yerda." action={<Link to="/app/analyses/new"><Button type="primary" icon={<PlusOutlined/>}>Yangi tahlil</Button></Link>}/><div className="surface"><div className="filter-bar"><Select aria-label="Holat bo‘yicha filter" allowClear placeholder="Barcha holatlar" value={status} onChange={v => { setStatus(v); resetPage(); }} options={[{ value: 'DRAFT', label: 'Qoralama' }, { value: 'QUEUED', label: 'Navbatda' }, { value: 'RUNNING', label: 'Jarayonda' }, { value: 'FINISHED', label: 'Yakunlangan' }, { value: 'FAILED', label: 'Bajarilmadi' }, { value: 'CANCELLED', label: 'Bekor qilingan' }]}/><Select aria-label="Xavf bo‘yicha filter" allowClear placeholder="Barcha xavf darajalari" value={risk} onChange={v => { setRisk(v); resetPage(); }} options={[{ value: 'LOW', label: 'Past' }, { value: 'MEDIUM', label: 'O‘rta' }, { value: 'HIGH', label: 'Yuqori' }, { value: 'NOT_ASSESSED', label: 'Baholanmagan' }]}/><Select aria-label="Kuzatilayotgan joy" allowClear placeholder="Barcha joylar" value={caseId} onChange={v => { setCaseId(v); resetPage(); }} options={cases.data?.items.map(c => ({ value: c.id, label: c.label }))}/><Input type="date" aria-label="Boshlanish sanasi" value={dateFrom} onChange={e => { setDateFrom(e.target.value); resetPage(); }}/><Input type="date" aria-label="Tugash sanasi" value={dateTo} onChange={e => { setDateTo(e.target.value); resetPage(); }}/></div>{history.isPending ? <Loading/> : history.isError ? <Failure error={history.error} retry={() => { void history.refetch(); }}/> : !history.data.items.length ? <EmptyAnalyses/> : <div className="analysis-list">{history.data.items.map(a => <Link className="analysis-row" to={`/app/analyses/${a.id}`} key={a.id}><span className="row-icon">{a.images[0] ? <AssetImage id={a.images[0].id} alt={a.isDemo ? "Demo illustratsiya" : "Kuzatuv surati"}/> : <FileImageOutlined/>}</span><span className="row-main"><strong>{a.case?.label ?? 'Teri kuzatuvi'}{a.isDemo && <DemoBadge/>}</strong><small>{a.case?.bodyLocation} · {date(a.createdAt)}</small></span><Status value={a.outcome || a.processingStatus}/>{a.result && <Status value={a.result.riskLevel}/>}<ArrowRightOutlined/></Link>)}</div>}<div className="pagination"><Button disabled={cursors.length < 2} onClick={() => setCursors(c => c.slice(0, -1))}>Oldingi</Button><span>{cursors.length}-sahifa</span><Button disabled={!history.data?.nextCursor} onClick={() => setCursors(c => [...c, history.data!.nextCursor!])}>Keyingi</Button></div></div></>;
}
